Simplify unit tests; never raise exceptions
Also, simplify `.str` handling. So much less code now!

Fixes error on production:

Traceback (most recent call last):
  File "/app/server/models/loaded_module.py", line 185, in render
    out = self.render_impl(arg1, arg2, **kwargs)
  File "/app/importedmodules/regexextractor/51c02e3/regexextractor.py", line 24, in render
    raise ValueError('You need to specify one (and only one) capture group in your regular expression.')
ValueError: You need to specify one (and only one) capture group in your regular expression.